[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.0.0"
itertools = "*"
nom = "7.0.0"
num = "*"

[dependencies.coordinates]
path = "../../coordinates.rs"
version = "0.4"
