[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoclib"
path = "src/lib.rs"

[dependencies]
regex = "1.0.0"
itertools = "*"
nom = "7.0.0"
num = "*"
rayon = "1.10"

[dependencies.coordinates]
path = "../../coordinates.rs"
version = "0.4"
